name: Build
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: sudo apt-get update -qq && sudo apt-get install -y -qq gcc flex bison bc libssl-dev
    - name: Setup Proton Clang
      run: |
        git clone --depth=1 https://github.com/kdrag0n/proton-clang.git proton-clang
        echo "PATH=$(pwd)/proton-clang/bin:\$PATH" >> \$GITHUB_ENV
    - name: Fetch KernelSU
      run: curl -LSs https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh | bash -s v0.9.5
    - name: Configure
      run: |
        export ARCH=arm64
        make ares_user_defconfig CC=clang
        scripts/config --enable KALLSYMS_ALL
        scripts/config --set-str LOCALVERSION "-ksu"
        scripts/config --disable CC_WERROR
        make olddefconfig CC=clang
    - name: Build
      run: |
        export ARCH=arm64
        make -j\$(nproc) CC=clang LD=ld.lld CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu-
    - uses: actions/upload-artifact@v4
      with: {name: Image, path: arch/arm64/boot/Image}
